kind: Service
apiVersion: v1
metadata:
  name: gettingstarted
  namespace: container-getting-started
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    deployment: gettingstarted
  type: LoadBalancer

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: gettingstarted
  namespace: container-getting-started
  labels:
    app: gettingstarted
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: gettingstarted
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: gettingstarted
    spec:
      containers:
        - name: gettingstarted
          image: docker.io/altugyildirim/getting-started:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          env:
          - name: "PASSWORD"
            value: "p@ssword123!"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600